
[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_ServerSettings")]
class ArcGIS_ServerSettings : OMI_BaseResource
{
	[Key] String ServerHostName;
	[Write, EmbeddedInstance("MSFT_Credential")] String SiteAdministrator;
	[Key, ValueMap{"Server","NotebookServer","MissionServer","VideoServer","DataPipelinesServer"}, Values{"Server","NotebookServer","MissionServer","VideoServer","DataPipelinesServer"}] String ServerType;
	[Write] String WebContextURL;	
	[Write, Description("Is Service Directory Disabled")] Boolean DisableServiceDirectory;
	[Write] String SharedKey;
	[Write] String HttpProxyHost;
	[Write] UInt32 HttpProxyPort;
	[Write, EmbeddedInstance("MSFT_Credential")] String HttpProxyCredential;
	[Write] String HttpsProxyHost;
	[Write] UInt32 HttpsProxyPort;
	[Write, EmbeddedInstance("MSFT_Credential")] String HttpsProxyCredential;
	[Write] String NonProxyHosts;
	[Write] String WebSocketContextURL;
	[Write] Boolean DisableDockerHealthCheck;
	[Write] String VideoServerLiveStreamGatewayHostname;
	[Write] String VideoServerLiveStreamPorts;
};