[ClassVersion("1.0.0.0"), FriendlyName("ArcGIS_ServerUpgrade")]
class ArcGIS_ServerUpgrade : OMI_BaseResource
{
	[Key] String ServerHostName;
	[Key, ValueMap{"Server","NotebookServer","MissionServer","VideoServer","DataPipelinesServer"}, Values{"Server","NotebookServer","MissionServer","VideoServer","DataPipelinesServer"}] String ServerType;
	[Write] String Version;
	[Write] Boolean EnableUpgradeSiteDebug;
};

